name: Build and publish  docker image

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/lukaspanni/couchdb-for-livesync:latest
  deploy:
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' || github.event_name =='schedule' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Deployment
        env: 
          GH_TOKEN: ${{ secrets.CD_TOKEN }}
        run: |
           gh api repos/lukaspanni/infrastructure/dispatches --input - <<< '{"event_type": "${{ github.event.repository.name }}", "client_payload": { "kubernetes-config": "couchdb.yml", "image-name": "ghcr.io/lukaspanni/ghcr.io/lukaspanni/couchdb-for-livesync" }'
          
